from ._AddCO2Source import *
from ._AddRfidTag import *
from ._AddSoundSource import *
from ._AddThermalSource import *
from ._DeleteCO2Source import *
from ._DeleteRfidTag import *
from ._DeleteSoundSource import *
from ._DeleteThermalSource import *
from ._LoadExternalMap import *
from ._LoadMap import *
from ._MoveRobot import *
from ._RegisterGui import *
