# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from stdr_msgs/KinematicMsg.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class KinematicMsg(genpy.Message):
  _md5sum = "75d30a9f55f18dd9353f0abaabfaf261"
  _type = "stdr_msgs/KinematicMsg"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Container for the kinematic model parameters. The parameters selected/
# are quite general. For a more accurate motion model a per-kinematic model
# approach should be followed.
# Parameters are in the form a_C_D, where C is affected by D.
# ux is the linear speed
# uy is the lateral speed (for omni vehicles)
# w is the angular speed
# g is a cofficient that directly affects the angular speed
# For more information check the MotionController::sampleVelocities function.

string type
float32 a_ux_ux
float32 a_ux_uy
float32 a_ux_w
float32 a_uy_ux
float32 a_uy_uy
float32 a_uy_w
float32 a_w_ux
float32 a_w_uy
float32 a_w_w
float32 a_g_ux
float32 a_g_uy
float32 a_g_w
"""
  __slots__ = ['type','a_ux_ux','a_ux_uy','a_ux_w','a_uy_ux','a_uy_uy','a_uy_w','a_w_ux','a_w_uy','a_w_w','a_g_ux','a_g_uy','a_g_w']
  _slot_types = ['string','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       type,a_ux_ux,a_ux_uy,a_ux_w,a_uy_ux,a_uy_uy,a_uy_w,a_w_ux,a_w_uy,a_w_w,a_g_ux,a_g_uy,a_g_w

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(KinematicMsg, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.type is None:
        self.type = ''
      if self.a_ux_ux is None:
        self.a_ux_ux = 0.
      if self.a_ux_uy is None:
        self.a_ux_uy = 0.
      if self.a_ux_w is None:
        self.a_ux_w = 0.
      if self.a_uy_ux is None:
        self.a_uy_ux = 0.
      if self.a_uy_uy is None:
        self.a_uy_uy = 0.
      if self.a_uy_w is None:
        self.a_uy_w = 0.
      if self.a_w_ux is None:
        self.a_w_ux = 0.
      if self.a_w_uy is None:
        self.a_w_uy = 0.
      if self.a_w_w is None:
        self.a_w_w = 0.
      if self.a_g_ux is None:
        self.a_g_ux = 0.
      if self.a_g_uy is None:
        self.a_g_uy = 0.
      if self.a_g_w is None:
        self.a_g_w = 0.
    else:
      self.type = ''
      self.a_ux_ux = 0.
      self.a_ux_uy = 0.
      self.a_ux_w = 0.
      self.a_uy_ux = 0.
      self.a_uy_uy = 0.
      self.a_uy_w = 0.
      self.a_w_ux = 0.
      self.a_w_uy = 0.
      self.a_w_w = 0.
      self.a_g_ux = 0.
      self.a_g_uy = 0.
      self.a_g_w = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12f().pack(_x.a_ux_ux, _x.a_ux_uy, _x.a_ux_w, _x.a_uy_ux, _x.a_uy_uy, _x.a_uy_w, _x.a_w_ux, _x.a_w_uy, _x.a_w_w, _x.a_g_ux, _x.a_g_uy, _x.a_g_w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.type = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.a_ux_ux, _x.a_ux_uy, _x.a_ux_w, _x.a_uy_ux, _x.a_uy_uy, _x.a_uy_w, _x.a_w_ux, _x.a_w_uy, _x.a_w_w, _x.a_g_ux, _x.a_g_uy, _x.a_g_w,) = _get_struct_12f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_12f().pack(_x.a_ux_ux, _x.a_ux_uy, _x.a_ux_w, _x.a_uy_ux, _x.a_uy_uy, _x.a_uy_w, _x.a_w_ux, _x.a_w_uy, _x.a_w_w, _x.a_g_ux, _x.a_g_uy, _x.a_g_w))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.type = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.a_ux_ux, _x.a_ux_uy, _x.a_ux_w, _x.a_uy_ux, _x.a_uy_uy, _x.a_uy_w, _x.a_w_ux, _x.a_w_uy, _x.a_w_w, _x.a_g_ux, _x.a_g_uy, _x.a_g_w,) = _get_struct_12f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12f = None
def _get_struct_12f():
    global _struct_12f
    if _struct_12f is None:
        _struct_12f = struct.Struct("<12f")
    return _struct_12f
