; Auto-generated. Do not edit!


(cl:in-package stdr_msgs-msg)


;//! \htmlinclude DeleteRobotFeedback.msg.html

(cl:defclass <DeleteRobotFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DeleteRobotFeedback (<DeleteRobotFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DeleteRobotFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DeleteRobotFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name stdr_msgs-msg:<DeleteRobotFeedback> is deprecated: use stdr_msgs-msg:DeleteRobotFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DeleteRobotFeedback>) ostream)
  "Serializes a message object of type '<DeleteRobotFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DeleteRobotFeedback>) istream)
  "Deserializes a message object of type '<DeleteRobotFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DeleteRobotFeedback>)))
  "Returns string type for a message object of type '<DeleteRobotFeedback>"
  "stdr_msgs/DeleteRobotFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DeleteRobotFeedback)))
  "Returns string type for a message object of type 'DeleteRobotFeedback"
  "stdr_msgs/DeleteRobotFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DeleteRobotFeedback>)))
  "Returns md5sum for a message object of type '<DeleteRobotFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DeleteRobotFeedback)))
  "Returns md5sum for a message object of type 'DeleteRobotFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DeleteRobotFeedback>)))
  "Returns full string definition for message of type '<DeleteRobotFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DeleteRobotFeedback)))
  "Returns full string definition for message of type 'DeleteRobotFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DeleteRobotFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DeleteRobotFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'DeleteRobotFeedback
))
