; Auto-generated. Do not edit!


(cl:in-package stdr_msgs-msg)


;//! \htmlinclude SpawnRobotFeedback.msg.html

(cl:defclass <SpawnRobotFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass SpawnRobotFeedback (<SpawnRobotFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SpawnRobotFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SpawnRobotFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name stdr_msgs-msg:<SpawnRobotFeedback> is deprecated: use stdr_msgs-msg:SpawnRobotFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SpawnRobotFeedback>) ostream)
  "Serializes a message object of type '<SpawnRobotFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SpawnRobotFeedback>) istream)
  "Deserializes a message object of type '<SpawnRobotFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SpawnRobotFeedback>)))
  "Returns string type for a message object of type '<SpawnRobotFeedback>"
  "stdr_msgs/SpawnRobotFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SpawnRobotFeedback)))
  "Returns string type for a message object of type 'SpawnRobotFeedback"
  "stdr_msgs/SpawnRobotFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SpawnRobotFeedback>)))
  "Returns md5sum for a message object of type '<SpawnRobotFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SpawnRobotFeedback)))
  "Returns md5sum for a message object of type 'SpawnRobotFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SpawnRobotFeedback>)))
  "Returns full string definition for message of type '<SpawnRobotFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SpawnRobotFeedback)))
  "Returns full string definition for message of type 'SpawnRobotFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SpawnRobotFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SpawnRobotFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SpawnRobotFeedback
))
